// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Lab2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lab2() {
    driver.get("https://tutorialsninja.com/demo/index.php");
    driver.manage().window().setSize(new Dimension(793, 816));
    driver.findElement(By.cssSelector(".swiper-viewport:nth-child(1) .swiper-button-next")).click();
    driver.findElement(By.cssSelector(".swiper-viewport:nth-child(1) .swiper-button-next")).click();
    driver.findElement(By.cssSelector(".swiper-viewport:nth-child(1) .swiper-button-next")).click();
    driver.findElement(By.cssSelector(".swiper-viewport:nth-child(1) .swiper-button-prev")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".swiper-viewport:nth-child(1) .swiper-button-next"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".product-layout:nth-child(1) .img-responsive")).click();
  }
}
